# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbfd8b03f2a4ea625284a1ceea0c13c630fe62a06675f624ec1e94367f67965ab507c5083b711221af0b58a45c617ac203608da060d9cd6d899be99d62388ff1

test:
  secret_key_base: 4a2d9440ea7c698b2963aba73cb27c6c0506dc647ccaa7d99190330e6d565c6b32b96aa838a4d6bc7b9f6c874c5a506df937881cc5435edf8b2f0d5219300fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
